name: wfssback
channels:
  - conda-forge
dependencies:
- python==3.12.* # Required by JWST pipeline
- sep
- astropy
- photutils
- scikit-image
- pip:
  - maskfill
  - git+https://github.com/spacetelescope/jwst.git
